FROM openjdk:17

RUN mkdir -p /app

WORKDIR /app

RUN curl https://piston-data.mojang.com/v1/objects/0bc471b96bb0edbc2f03e6cdc3ad981f7a4f5f8a/server.jar --output server.jar

COPY eula.txt ops.json whitelist.json ./
COPY 1.20/server.properties ./

RUN mkdir world

CMD [  "java", "-Xms4G", "-Xmx5G", "-jar", "server.jar", "nogui"  ]
