FROM openjdk:17

RUN mkdir -p /app

WORKDIR /app

RUN curl https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar --output server.jar

COPY eula.txt ops.json whitelist.json ./
COPY 1.20.1/server.properties ./

RUN mkdir world

CMD [  "java", "-Xms4G", "-Xmx5G", "-jar", "server.jar", "nogui"  ]
