version: "3.8"
services:
  better_minecraft:
    build:
      context: ./
      dockerfile: Dockerfile.better_minecraft
    image: minecraft:better_minecraft
    ports:
      - 25566:25565
    volumes:
      - ./better_minecraft/world:/app/world/
      - ./backups/better_minecraft:/app/backups
    deploy:
      restart_policy:
        condition: on-failure
