FROM openjdk:latest

RUN mkdir -p /app

WORKDIR /app

RUN curl https://launcher.mojang.com/v1/objects/f238cf129a0848effe5037d8aaefe3f1f350b689/server.jar --output server.jar

COPY eula.txt ops.json ./
COPY snapshot/server.properties ./

RUN mkdir world

CMD [  "java", "-Xms4G", "-Xmx5G", "-jar", "server.jar", "nogui"  ]
