FROM eclipse-temurin:17-jre-focal AS build

RUN apt-get -y update && \
  apt-get -y install curl unzip

RUN mkdir -p /build

WORKDIR /build

RUN curl https://mediafilez.forgecdn.net/files/5614/632/BCG%2B%202.5.1%20Server%20Files.zip --output files.zip && \
  unzip files.zip && \
  rm -rf files.zip

RUN mkdir -p /app

WORKDIR /app

RUN cp -r /build/* .
COPY eula.txt ops.json whitelist.json atm9/server.properties ./

RUN mkdir world
RUN chmod +x ./start.sh

CMD ["/app/start.sh"]
