version: "3.8"
services:
  better_minecraft:
    build:
      context: ./
      dockerfile: Dockerfile.better_minecraft
    image: minecraft:better_minecraft
    ports:
      - 25565:25565
    volumes:
      - ./better_minecraft/world:/app/world/
      - ./backups/better_minecraft:/app/backups
      - ./better_minecraft/logs:/app/logs
      - ./better_minecraft/crash-reports:/app/crash-reports
    deploy:
      restart_policy:
        condition: on-failure
