version: "3.8"
services:
  better_minecraft:
    build:
      context: ./
      dockerfile: Dockerfile.better_minecraft
    image: minecraft:better_minecraft
    ports:
      - 25566:25566
    volumes:
      - ./better_minecraft/world:/app/world/
      - ./backups/better_minecraft:/app/backups
      - ./better_minecraft/logs:/app/logs
      - ./better_minecraft/crash-reports:/app/crash-reports
    deploy:
      restart_policy:
        condition: on-failure
  v1_18:
    build:
      context: ./
      dockerfile: Dockerfile.1.18
    image: minecraft:1.18
    ports:
      - 25565:25565
    volumes:
      - ./1.18/world:/app/world/
      - ./1.18/logs:/app/logs
      - ./1.18/crash-reports:/app/crash-reports
    
  
