FROM openjdk:17

RUN mkdir -p /app

WORKDIR /app

RUN curl https://launcher.mojang.com/v1/objects/5889357fe058d867f6e27ee3f033286c430ec91e/server.jar --output server.jar

COPY eula.txt ops.json ./
COPY 1.18/server.properties ./

RUN mkdir world

CMD [  "java", "-Xms4G", "-Xmx5G", "-jar", "server.jar", "nogui"  ]
